### ISSUE TITLE
AngioTK Documentation

### ISSUE THREAD

**Issue by aancel** [feelpp/angiotk#10]
Documentation for AngioTK:
- [x] Build instructions
- [x] General description of AngioTK
- [x] Description of the different modules
  - [x] Input and output of the modules
  - [x] Document the different options available
- [x] Document the graphical tool for editing centerlines
- [x] Document how output files are stored for the Pipeline and how files are stored for the result matrix
- [ ] Creation of Angiotk Book

**Comment by francoisdh** [comment]
Since the AngioTK Book system was abandoned and we moved to Antora, we can close this issue.
